name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write # Needed to create releases

jobs:
  build:
    runs-on: macos-13 # Intel-based runner for better compatibility

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive


    - name: Build GLFW from source (Universal)
      run: |
        git clone https://github.com/glfw/glfw.git
        cd glfw
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15
        make -j$(sysctl -n hw.ncpu)
        sudo make install

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_CXX_FLAGS="-DGL_SILENCE_DEPRECATION" -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"


    - name: Build
      run: |
        cd build
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cheat-dylib
        path: build/cheat.dylib

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: build/cheat.dylib
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

